export type LocationType =
  | "airport"
  | "corporate"
  | "hotel"
  | "landmark"
  | "mall"
  | "restaurant"
  | "station"
  | "general";

export interface LocationOption {
  id: string;
  name: string;
  address: string;
  type: LocationType;
  lat: number;
  lng: number;
}

export const INDONESIA_LOCATIONS: LocationOption[] = [
  // ===== AIRPORTS =====
  {
    id: "cgk-airport",
    name: "Soekarno-Hatta Int'l Airport (CGK)",
    address: "Jl. Peta Barat, Cengkareng, Tangerang, Banten",
    type: "airport",
    lat: -6.1256,
    lng: 106.6558,
  },
  {
    id: "hlp-airport",
    name: "Halim Perdanakusuma Airport (HLP)",
    address: "Jl. Protokol Halim Perdanakusuma, Makasar, Jakarta Timur",
    type: "airport",
    lat: -6.2681,
    lng: 106.8926,
  },
  {
    id: "dps-airport",
    name: "Ngurah Rai Int'l Airport (DPS)",
    address: "Jl. Raya Ngurah Rai, Tuban, Badung, Bali",
    type: "airport",
    lat: -8.7481,
    lng: 115.167,
  },
  {
    id: "sub-airport",
    name: "Juanda Int'l Airport (SUB)",
    address: "Jl. Ir. H. Juanda, Sedati, Sidoarjo, Jawa Timur",
    type: "airport",
    lat: -7.3798,
    lng: 112.7869,
  },
  {
    id: "kno-airport",
    name: "Kualanamu Int'l Airport (KNO)",
    address: "Jl. Bandara Kualanamu, Deli Serdang, Sumatera Utara",
    type: "airport",
    lat: 3.6424,
    lng: 98.8853,
  },
  {
    id: "upg-airport",
    name: "Sultan Hasanuddin Airport (UPG)",
    address: "Jl. Bandara Sultan Hasanuddin, Maros, Sulawesi Selatan",
    type: "airport",
    lat: -5.0617,
    lng: 119.5546,
  },
  {
    id: "srg-airport",
    name: "Ahmad Yani Airport (SRG)",
    address: "Jl. Letjen S. Parman, Ngaliyan, Semarang, Jawa Tengah",
    type: "airport",
    lat: -6.9655,
    lng: 110.3748,
  },
  {
    id: "jog-airport",
    name: "Adisutjipto Airport (JOG)",
    address: "Jl. Solo, Ring Road Timur, Yogyakarta",
    type: "airport",
    lat: -7.7881,
    lng: 110.4317,
  },
  {
    id: "bdo-airport",
    name: "Husein Sastranegara Airport (BDO)",
    address: "Jl. Pajajaran No. 156, Bandung, Jawa Barat",
    type: "airport",
    lat: -6.9006,
    lng: 107.5763,
  },

  // ===== CORPORATE TOWERS & OFFICES =====
  {
    id: "parago-hq",
    name: "ParaGo HQ - Corporate Tower",
    address: "Jl. H.R. Rasuna Said Block X-5, Kuningan, Jakarta Selatan",
    type: "corporate",
    lat: -6.2185,
    lng: 106.8332,
  },
  {
    id: "equity-tower",
    name: "SCBD Equity Tower",
    address: "Jl. Jend. Sudirman Kav. 52-53, Senayan, Jakarta Selatan",
    type: "corporate",
    lat: -6.2232,
    lng: 106.8145,
  },
  {
    id: "menara-bca",
    name: "Grand Indonesia Menara BCA",
    address: "Jl. M.H. Thamrin No. 1, Gambir, Jakarta Pusat",
    type: "corporate",
    lat: -6.1937,
    lng: 106.8231,
  },
  {
    id: "bsd-office-park",
    name: "BSD Green Office Park 6",
    address: "Jl. BSD Grand Boulevard, Sampora, Tangerang Selatan",
    type: "corporate",
    lat: -6.2982,
    lng: 106.6754,
  },
  {
    id: "wisma-46",
    name: "Wisma 46 - Kota BNI",
    address: "Jl. Jend. Sudirman Kav. 1, Tanah Abang, Jakarta Pusat",
    type: "corporate",
    lat: -6.2018,
    lng: 106.8221,
  },
  {
    id: "menara-astra",
    name: "Menara Astra",
    address: "Jl. Jend. Sudirman Kav. 5-6, Kuningan, Jakarta Selatan",
    type: "corporate",
    lat: -6.2237,
    lng: 106.8128,
  },
  {
    id: "wtc-jakarta",
    name: "World Trade Center (WTC) Jakarta",
    address: "Jl. Jend. Sudirman Kav. 29-31, Kuningan, Jakarta Selatan",
    type: "corporate",
    lat: -6.2165,
    lng: 106.8151,
  },
  {
    id: "menara-rajawali",
    name: "Menara Rajawali",
    address: "SCBD, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan",
    type: "corporate",
    lat: -6.2244,
    lng: 106.813,
  },
  {
    id: "menara-imperium",
    name: "Menara Imperium",
    address: "Jl. H.R. Rasuna Said Kav. 1, Kuningan, Jakarta Selatan",
    type: "corporate",
    lat: -6.2251,
    lng: 106.835,
  },
  {
    id: "idx-building",
    name: "Indonesia Stock Exchange (IDX) Tower",
    address: "Jl. Jend. Sudirman Kav. 52-53, SCBD, Jakarta Selatan",
    type: "corporate",
    lat: -6.2248,
    lng: 106.8335,
  },

  // ===== HOTELS =====
  {
    id: "kempinski",
    name: "Hotel Indonesia Kempinski",
    address: "Jl. M.H. Thamrin No. 1, Menteng, Jakarta Pusat",
    type: "hotel",
    lat: -6.1944,
    lng: 106.8229,
  },
  {
    id: "ritz-carlton-pp",
    name: "The Ritz-Carlton Jakarta, Pacific Place",
    address: "SCBD, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan",
    type: "hotel",
    lat: -6.2241,
    lng: 106.8152,
  },
  {
    id: "raffles-jakarta",
    name: "Raffles Jakarta",
    address: "Jl. Jend. Sudirman Kav. 52-53, SCBD, Jakarta Selatan",
    type: "hotel",
    lat: -6.2237,
    lng: 106.8161,
  },
  {
    id: "westin-jakarta",
    name: "The Westin Jakarta (Gama Tower)",
    address: "Jl. H.R. Rasuna Said Kav. 8-9, Kuningan, Jakarta Selatan",
    type: "hotel",
    lat: -6.2209,
    lng: 106.8119,
  },
  {
    id: "shangrila-jakarta",
    name: "Shangri-La Jakarta",
    address: "Jl. Jend. Sudirman Kav. 1, Tanah Abang, Jakarta Pusat",
    type: "hotel",
    lat: -6.2125,
    lng: 106.8129,
  },
  {
    id: "grand-hyatt-jakarta",
    name: "Grand Hyatt Jakarta",
    address: "Jl. M.H. Thamrin No. 9, Thamrin, Jakarta Pusat",
    type: "hotel",
    lat: -6.1897,
    lng: 106.8242,
  },
  {
    id: "mandarin-jakarta",
    name: "Mandarin Oriental Jakarta",
    address: "Jl. Jend. Sudirman Kav. 52-53, SCBD, Jakarta Selatan",
    type: "hotel",
    lat: -6.2244,
    lng: 106.8158,
  },
  {
    id: "sultan-hotel",
    name: "The Sultan Hotel & Residence",
    address: "Jl. Jend. Gatot Subroto Kav. 27, Senayan, Jakarta Selatan",
    type: "hotel",
    lat: -6.2234,
    lng: 106.8078,
  },
  {
    id: "jw-marriott-jakarta",
    name: "JW Marriott Hotel Jakarta",
    address: "Jl. DR. Ide Anak Agung Gde Agung Kav. 26, Setiabudi, Jakarta Selatan",
    type: "hotel",
    lat: -6.2241,
    lng: 106.8104,
  },
  {
    id: "mulia-senayan",
    name: "Hotel Mulia Senayan",
    address: "Jl. Asia Afrika, Senayan, Jakarta Pusat",
    type: "hotel",
    lat: -6.2141,
    lng: 106.8127,
  },
  {
    id: "fairmont-jakarta",
    name: "Fairmont Jakarta",
    address: "Jl. Asia Afrika No. 8, Senayan, Jakarta Pusat",
    type: "hotel",
    lat: -6.2239,
    lng: 106.8127,
  },
  {
    id: "ayana-midplaza",
    name: "Ayana Midplaza Jakarta",
    address: "Jl. Jend. Sudirman Kav. 10-11, Karet Tengsin, Jakarta Pusat",
    type: "hotel",
    lat: -6.2293,
    lng: 106.8213,
  },

  // ===== LANDMARKS, TEMPLES & TOURIST SPOTS =====
  {
    id: "monas",
    name: "Monas - National Monument",
    address: "Gambir, Jakarta Pusat, DKI Jakarta",
    type: "landmark",
    lat: -6.1754,
    lng: 106.8272,
  },
  {
    id: "istiqlal-mosque",
    name: "Istiqlal Mosque",
    address: "Jl. Taman Wijaya Kusuma, Gambir, Jakarta Pusat",
    type: "landmark",
    lat: -6.1701,
    lng: 106.8308,
  },
  {
    id: "jakarta-cathedral",
    name: "Jakarta Cathedral",
    address: "Jl. Katedral No. 7B, Sawah Besar, Jakarta Pusat",
    type: "landmark",
    lat: -6.1689,
    lng: 106.8333,
  },
  {
    id: "kota-tua",
    name: "Kota Tua Jakarta (Old Town)",
    address: "Jl. Taman Fatahillah, Taman Sari, Jakarta Barat",
    type: "landmark",
    lat: -6.1351,
    lng: 106.8147,
  },
  {
    id: "museum-fatahillah",
    name: "Museum Fatahillah (Jakarta History Museum)",
    address: "Jl. Taman Fatahillah No. 1, Jakarta Barat",
    type: "landmark",
    lat: -6.1355,
    lng: 106.8156,
  },
  {
    id: "national-museum",
    name: "National Museum of Indonesia",
    address: "Jl. Medan Merdeka Barat No. 12, Gambir, Jakarta Pusat",
    type: "landmark",
    lat: -6.1765,
    lng: 106.8218,
  },
  {
    id: "gbk-stadium",
    name: "Gelora Bung Karno (GBK) Main Stadium",
    address: "Jl. Pintu Satu Senayan, Tanah Abang, Jakarta Pusat",
    type: "landmark",
    lat: -6.2193,
    lng: 106.8058,
  },
  {
    id: "bundaran-hi",
    name: "Bundaran HI (Hotel Indonesia Roundabout)",
    address: "Jl. M.H. Thamrin, Menteng, Jakarta Pusat",
    type: "landmark",
    lat: -6.1946,
    lng: 106.8226,
  },
  {
    id: "kebun-raya-bogor",
    name: "Kebun Raya Bogor (Bogor Botanical Gardens)",
    address: "Jl. Ir. H. Juanda No. 13, Bogor Tengah, Jawa Barat",
    type: "landmark",
    lat: -6.5986,
    lng: 106.7969,
  },
  {
    id: "istana-bogor",
    name: "Bogor Presidential Palace",
    address: "Jl. Ir. H. Juanda No. 1, Bogor Tengah, Jawa Barat",
    type: "landmark",
    lat: -6.5978,
    lng: 106.7987,
  },
  {
    id: "ragunan-zoo",
    name: "Ragunan Wildlife Park (Zoo)",
    address: "Jl. Harsono RM No. 1, Pasar Minggu, Jakarta Selatan",
    type: "landmark",
    lat: -6.3122,
    lng: 106.8209,
  },
  {
    id: "tmii",
    name: "Taman Mini Indonesia Indah (TMII)",
    address: "Jl. Taman Mini Indonesia Indah, Cipayung, Jakarta Timur",
    type: "landmark",
    lat: -6.3023,
    lng: 106.8954,
  },
  {
    id: "dufan-ancol",
    name: "Dunia Fantasi (Dufan), Ancol",
    address: "Jl. Lodan Timur No. 7, Pademangan, Jakarta Utara",
    type: "landmark",
    lat: -6.1222,
    lng: 106.8337,
  },
  {
    id: "sunda-kelapa",
    name: "Sunda Kelapa Harbor",
    address: "Jl. Sunda Kelapa, Penjaringan, Jakarta Utara",
    type: "landmark",
    lat: -6.1277,
    lng: 106.8069,
  },
  {
    id: "museum-macan",
    name: "Museum MACAN (Modern Art Nusantara)",
    address: "AKR Tower, Jl. Panjang No. 5, Kebon Jeruk, Jakarta Barat",
    type: "landmark",
    lat: -6.188,
    lng: 106.79,
  },
  {
    id: "borobudur",
    name: "Borobudur Temple",
    address: "Jl. Badrawati, Borobudur, Magelang, Jawa Tengah",
    type: "landmark",
    lat: -7.6079,
    lng: 110.2037,
  },
  {
    id: "prambanan",
    name: "Prambanan Temple",
    address: "Jl. Raya Solo-Yogyakarta, Prambanan, Sleman, Yogyakarta",
    type: "landmark",
    lat: -7.752,
    lng: 110.4914,
  },
  {
    id: "kraton-yogya",
    name: "Kraton Yogyakarta (Yogyakarta Palace)",
    address: "Jl. Rotowijayan 1, Panembahan, Yogyakarta",
    type: "landmark",
    lat: -6.811,
    lng: 110.359,
  },
  {
    id: "malioboro",
    name: "Malioboro Street",
    address: "Jl. Malioboro, Yogyakarta",
    type: "landmark",
    lat: -6.7664,
    lng: 110.3598,
  },
  {
    id: "tugu-yogya",
    name: "Tugu Yogyakarta",
    address: "Jl. Pangeran Mangkubumi, Yogyakarta",
    type: "landmark",
    lat: -6.7167,
    lng: 110.3664,
  },
  {
    id: "taman-sari",
    name: "Taman Sari Water Castle",
    address: "Jl. Taman Sari, Patehan, Yogyakarta",
    type: "landmark",
    lat: -6.7991,
    lng: 110.3574,
  },
  {
    id: "gedung-sate",
    name: "Gedung Sate (West Java Governor Office)",
    address: "Jl. Diponegoro No. 22, Bandung, Jawa Barat",
    type: "landmark",
    lat: -6.9014,
    lng: 107.6187,
  },
  {
    id: "gedung-merdeka",
    name: "Gedung Merdeka (Asia Africa Conference)",
    address: "Jl. Asia Afrika No. 65, Braga, Bandung, Jawa Barat",
    type: "landmark",
    lat: -6.9212,
    lng: 107.6094,
  },
  {
    id: "braga-street",
    name: "Braga Street",
    address: "Jl. Braga, Sumur Bandung, Bandung, Jawa Barat",
    type: "landmark",
    lat: -6.9173,
    lng: 107.6091,
  },
  {
    id: "tangkuban-perahu",
    name: "Tangkuban Perahu Volcano",
    address: "Cikole, Lembang, Bandung Barat, Jawa Barat",
    type: "landmark",
    lat: -6.7712,
    lng: 107.6,
  },
  {
    id: "kawah-putih",
    name: "Kawah Putih Ciwidey",
    address: "Sugihmukti, Pasir Jambu, Bandung, Jawa Barat",
    type: "landmark",
    lat: -7.1664,
    lng: 107.4024,
  },
  {
    id: "lawang-sewu",
    name: "Lawang Sewu",
    address: "Jl. Pemuda, Semarang Tengah, Semarang, Jawa Tengah",
    type: "landmark",
    lat: -6.9973,
    lng: 110.4138,
  },
  {
    id: "sam-poo-kong",
    name: "Sam Poo Kong Temple",
    address: "Jl. Simongan No. 129, Semarang Barat, Semarang, Jawa Tengah",
    type: "landmark",
    lat: -6.9735,
    lng: 110.4139,
  },
  {
    id: "tugu-pahlawan",
    name: "Tugu Pahlawan Surabaya",
    address: "Jl. Pahlawan, Bubutan, Surabaya, Jawa Timur",
    type: "landmark",
    lat: -7.2434,
    lng: 112.7379,
  },
  {
    id: "monkasel",
    name: "Monkasel (Submarine Monument)",
    address: "Jl. Pemuda, Embong Kaliasin, Surabaya, Jawa Timur",
    type: "landmark",
    lat: -7.247,
    lng: 112.7382,
  },
  {
    id: "sampoerna-house",
    name: "House of Sampoerna",
    address: "Jl. Taman Sampoerna No. 6, Krembangan, Surabaya, Jawa Timur",
    type: "landmark",
    lat: -7.2315,
    lng: 112.7383,
  },
  {
    id: "tanah-lot",
    name: "Tanah Lot Temple",
    address: "Beraban, Kediri, Tabanan, Bali",
    type: "landmark",
    lat: -8.624,
    lng: 115.0881,
  },
  {
    id: "uluwatu",
    name: "Uluwatu Temple",
    address: "Pecatu, Kuta Selatan, Badung, Bali",
    type: "landmark",
    lat: -8.8291,
    lng: 115.0849,
  },
  {
    id: "gwk",
    name: "Garuda Wisnu Kencana (GWK) Cultural Park",
    address: "Jl. Raya Uluwatu, Ungasan, Badung, Bali",
    type: "landmark",
    lat: -8.8078,
    lng: 115.1615,
  },
  {
    id: "ubud-monkey-forest",
    name: "Ubud Monkey Forest (Sacred Monkey Forest)",
    address: "Jl. Monkey Forest, Ubud, Gianyar, Bali",
    type: "landmark",
    lat: -8.5193,
    lng: 115.2555,
  },
  {
    id: "ubud-palace",
    name: "Ubud Palace (Puri Saren Agung)",
    address: "Jl. Raya Ubud, Ubud, Gianyar, Bali",
    type: "landmark",
    lat: -8.5081,
    lng: 115.2622,
  },
  {
    id: "besakih",
    name: "Besakih Mother Temple (Pura Besakih)",
    address: "Besakih, Rendang, Karangasem, Bali",
    type: "landmark",
    lat: -8.3741,
    lng: 115.4515,
  },
  {
    id: "kuta-beach",
    name: "Kuta Beach",
    address: "Kuta, Badung, Bali",
    type: "landmark",
    lat: -8.7195,
    lng: 115.1631,
  },
  {
    id: "seminyak-beach",
    name: "Seminyak Beach",
    address: "Seminyak, Kuta, Badung, Bali",
    type: "landmark",
    lat: -8.6876,
    lng: 115.1568,
  },
  {
    id: "nusa-dua",
    name: "Nusa Dua Beach",
    address: "Benoa, Kuta Selatan, Badung, Bali",
    type: "landmark",
    lat: -8.7927,
    lng: 115.2251,
  },
  {
    id: "jimbaran-bay",
    name: "Jimbaran Bay",
    address: "Jimbaran, Kuta Selatan, Badung, Bali",
    type: "landmark",
    lat: -8.7849,
    lng: 115.161,
  },
  {
    id: "sanur-beach",
    name: "Sanur Beach",
    address: "Sanur, Denpasar Selatan, Denpasar, Bali",
    type: "landmark",
    lat: -8.6899,
    lng: 115.2598,
  },
  {
    id: "fort-rotterdam",
    name: "Fort Rotterdam (Benteng Ujung Pandang)",
    address: "Jl. Ujung Pandang No. 3, Bulo Gading, Makassar, Sulawesi Selatan",
    type: "landmark",
    lat: -5.1346,
    lng: 119.4113,
  },
  {
    id: "losari-beach",
    name: "Losari Beach (Pantai Losari)",
    address: "Jl. Penghibur, Losari, Makassar, Sulawesi Selatan",
    type: "landmark",
    lat: -5.1414,
    lng: 119.406,
  },
  {
    id: "maimum-palace",
    name: "Maimun Palace (Istana Maimun)",
    address: "Jl. Sultan Ma'moen Al Rasyid, Medan Maimun, Medan, Sumatera Utara",
    type: "landmark",
    lat: 3.5755,
    lng: 98.6839,
  },
  {
    id: "masjid-al-mashun",
    name: "Great Mosque of Medan (Masjid Raya Al-Mashun)",
    address: "Jl. Sisingamangaraja, Medan, Sumatera Utara",
    type: "landmark",
    lat: 3.5736,
    lng: 98.682,
  },
  {
    id: "suramadu-bridge",
    name: "Suramadu Bridge",
    address: "Surabaya - Madura, East Java",
    type: "landmark",
    lat: -7.2147,
    lng: 112.7391,
  },

  // ===== SHOPPING MALLS =====
  {
    id: "plaza-indonesia",
    name: "Plaza Indonesia",
    address: "Jl. M.H. Thamrin, Gambir, Jakarta Pusat",
    type: "mall",
    lat: -6.1931,
    lng: 106.8237,
  },
  {
    id: "plaza-senayan",
    name: "Plaza Senayan",
    address: "Jl. Asia Afrika No. 8, Senayan, Jakarta Pusat",
    type: "mall",
    lat: -6.2243,
    lng: 106.7977,
  },
  {
    id: "senayan-city",
    name: "Senayan City",
    address: "Jl. Asia Afrika Lot 19, Senayan, Jakarta Pusat",
    type: "mall",
    lat: -6.2255,
    lng: 106.7986,
  },
  {
    id: "pacific-place",
    name: "Pacific Place",
    address: "Jl. Jend. Sudirman Kav. 52-53, SCBD, Jakarta Selatan",
    type: "mall",
    lat: -6.2242,
    lng: 106.8138,
  },
  {
    id: "kota-kasablanka",
    name: "Kota Kasablanka",
    address: "Jl. Casablanca Raya Kav. 88, Tebet, Jakarta Selatan",
    type: "mall",
    lat: -6.2337,
    lng: 106.8157,
  },
  {
    id: "central-park",
    name: "Central Park Mall",
    address: "Jl. Letjen S. Parman Kav. 28, Tanjung Duren, Jakarta Barat",
    type: "mall",
    lat: -6.1768,
    lng: 106.79,
  },
  {
    id: "gandaria-city",
    name: "Gandaria City Mall",
    address: "Jl. Sultan Iskandar Muda, Kebayoran Lama, Jakarta Selatan",
    type: "mall",
    lat: -6.2419,
    lng: 106.7794,
  },
  {
    id: "blok-m-plaza",
    name: "Blok M Plaza",
    address: "Jl. Bulungan, Melawai, Jakarta Selatan",
    type: "mall",
    lat: -6.2447,
    lng: 106.7989,
  },
  {
    id: "mangga-dua-square",
    name: "Mangga Dua Square",
    address: "Jl. Raya Mangga Dua, Ancol, Jakarta Utara",
    type: "mall",
    lat: -6.1493,
    lng: 106.8269,
  },
  {
    id: "lippo-mall-puri",
    name: "Lippo Mall Puri",
    address: "Jl. Puri Indah Raya, Kembangan, Jakarta Barat",
    type: "mall",
    lat: -6.1705,
    lng: 106.745,
  },
  {
    id: "lippo-mall-kemang",
    name: "Lippo Mall Kemang",
    address: "Jl. Pangeran Antasari No. 36, Kemang, Jakarta Selatan",
    type: "mall",
    lat: -6.261,
    lng: 106.82,
  },
  {
    id: "pik-avenue",
    name: "PIK Avenue",
    address: "Jl. Pantai Indah Utara 2, Kamal Muara, Jakarta Utara",
    type: "mall",
    lat: -6.1051,
    lng: 106.7866,
  },
  {
    id: "aeon-bsd",
    name: "AEON Mall BSD City",
    address: "Jl. BSD Raya Utama, Lengkong Kulon, Tangerang Selatan",
    type: "mall",
    lat: -6.2947,
    lng: 106.6597,
  },
  {
    id: "teras-kota",
    name: "Teras Kota Supermall BSD",
    address: "Jl. Pahlawan Seribu, Lengkong Gudang, Tangerang Selatan",
    type: "mall",
    lat: -6.3024,
    lng: 106.6581,
  },
  {
    id: "tunjungan-plaza",
    name: "Tunjungan Plaza",
    address: "Jl. Basuki Rahmat No. 8-12, Genteng, Surabaya, Jawa Timur",
    type: "mall",
    lat: -7.2562,
    lng: 112.7434,
  },
  {
    id: "galaxy-mall",
    name: "Galaxy Mall Surabaya",
    address: "Jl. Dharmahusada Indah Timur No. 35, Mulyorejo, Surabaya",
    type: "mall",
    lat: -7.2787,
    lng: 112.7503,
  },
  {
    id: "pakuwon-mall",
    name: "Pakuwon Mall",
    address: "Jl. Puncak Indah Lontar, Wiyung, Surabaya, Jawa Timur",
    type: "mall",
    lat: -7.2866,
    lng: 112.686,
  },
  {
    id: "pvj-bandung",
    name: "Paris Van Java Mall",
    address: "Jl. Sukajadi No. 137-139, Sukajadi, Bandung, Jawa Barat",
    type: "mall",
    lat: -6.8907,
    lng: 107.5977,
  },
  {
    id: "trans-studio-bandung",
    name: "Trans Studio Mall Bandung",
    address: "Jl. Gatot Subroto No. 289, Cibangkong, Bandung, Jawa Barat",
    type: "mall",
    lat: -6.9214,
    lng: 107.6076,
  },
  {
    id: "beachwalk-bali",
    name: "Beachwalk Shopping Center",
    address: "Jl. Pantai Kuta No. 1, Kuta, Badung, Bali",
    type: "mall",
    lat: -8.7176,
    lng: 115.1688,
  },

  // ===== RESTAURANTS =====
  {
    id: "plataran-dharmawangsa",
    name: "Plataran Dharmawangsa",
    address: "Jl. Dharmawangsa Raya No. 1, Kebayoran Baru, Jakarta Selatan",
    type: "restaurant",
    lat: -6.2606,
    lng: 106.8086,
  },
  {
    id: "bunga-rampai",
    name: "Bunga Rampai",
    address: "Jl. Kemang Raya No. 3, Bangka, Jakarta Selatan",
    type: "restaurant",
    lat: -6.2598,
    lng: 106.8079,
  },
  {
    id: "lara-djonggrang",
    name: "Lara Djonggrang",
    address: "Jl. Teuku Cik Ditiro No. 4, Menteng, Jakarta Pusat",
    type: "restaurant",
    lat: -6.2116,
    lng: 106.8296,
  },
  {
    id: "social-house",
    name: "Social House",
    address: "Grand Indonesia, Jl. M.H. Thamrin No. 1, Jakarta Pusat",
    type: "restaurant",
    lat: -6.1937,
    lng: 106.8231,
  },
  {
    id: "sate-senayan",
    name: "Sate Khas Senayan",
    address: "Jl. Kebon Sirih No. 31, Jakarta Pusat",
    type: "restaurant",
    lat: -6.1832,
    lng: 106.8246,
  },
  {
    id: "bebek-bengil",
    name: "Bebek Bengil (Dirty Duck Diner) Ubud",
    address: "Jl. Hanoman, Padang Tegal, Ubud, Gianyar, Bali",
    type: "restaurant",
    lat: -8.5177,
    lng: 115.2563,
  },
  {
    id: "ibu-oka",
    name: "Warung Babi Guling Ibu Oka",
    address: "Jl. Suweta, Ubud, Gianyar, Bali",
    type: "restaurant",
    lat: -8.5084,
    lng: 115.2612,
  },
  {
    id: "mades-warung",
    name: "Made's Warung",
    address: "Jl. Raya Seminyak No. 66, Seminyak, Badung, Bali",
    type: "restaurant",
    lat: -8.6876,
    lng: 115.1568,
  },
  {
    id: "restoran-hajimemashite",
    name: "Hajimemashite",
    address: "Jl. Permata Berlian Utara 1, Mampang, Jakarta Selatan",
    type: "restaurant",
    lat: -6.2429,
    lng: 106.8196,
  },
  {
    id: "nate-jakarta",
    name: "Nante Jakarta (BNI 46)",
    address: "Wisma 46 Kota BNI, Jl. Jend. Sudirman Kav. 1, Jakarta Pusat",
    type: "restaurant",
    lat: -6.2018,
    lng: 106.8221,
  },
  {
    id: "lawless-cafe",
    name: "Lawless Cafe & Social Space",
    address: "Jl. Wijaya I No. 21, Melawai, Jakarta Selatan",
    type: "restaurant",
    lat: -6.2449,
    lng: 106.8081,
  },
  {
    id: "kafe-betawi",
    name: "Kafe Betawi (Tugu Kuningan)",
    address: "Jl. Tugu Kuningan, Pertokoan Toguan No. 5, Jakarta Selatan",
    type: "restaurant",
    lat: -6.233,
    lng: 106.836,
  },

  // ===== TRAIN & MRT STATIONS =====
  {
    id: "gambir-station",
    name: "Gambir Station",
    address: "Jl. Medan Merdeka Timur, Gambir, Jakarta Pusat",
    type: "station",
    lat: -6.1766,
    lng: 106.8301,
  },
  {
    id: "pasarsenen-station",
    name: "Pasar Senen Station",
    address: "Jl. Stasiun Senen No. 3, Senen, Jakarta Pusat",
    type: "station",
    lat: -6.1693,
    lng: 106.8455,
  },
  {
    id: "sudirman-station",
    name: "Sudirman Station",
    address: "Jl. Jend. Sudirman, Karet Tengsin, Jakarta Pusat",
    type: "station",
    lat: -6.2024,
    lng: 106.8222,
  },
  {
    id: "manggarai-station",
    name: "Manggarai Station",
    address: "Jl. Manggarai Utara, Tebet, Jakarta Selatan",
    type: "station",
    lat: -6.2097,
    lng: 106.8527,
  },
  {
    id: "bhi-mrt",
    name: "Bundaran HI MRT Station",
    address: "Jl. M.H. Thamrin, Menteng, Jakarta Pusat",
    type: "station",
    lat: -6.1946,
    lng: 106.8226,
  },
  {
    id: "blokm-mrt",
    name: "Blok M MRT Station",
    address: "Jl. Bulungan, Melawai, Jakarta Selatan",
    type: "station",
    lat: -6.2447,
    lng: 106.7987,
  },
  {
    id: "bandung-station",
    name: "Stasiun Bandung",
    address: "Jl. Stasiun Timur, Kebon Jeruk, Bandung, Jawa Barat",
    type: "station",
    lat: -6.9152,
    lng: 107.6042,
  },
  {
    id: "tugu-station",
    name: "Stasiun Tugu Yogyakarta",
    address: "Jl. Margo Utomo, Sosromenduran, Yogyakarta",
    type: "station",
    lat: -6.7866,
    lng: 110.388,
  },
  {
    id: "gubeng-station",
    name: "Stasiun Surabaya Gubeng",
    address: "Jl. Stasiun Gubeng No. 1, Gubeng, Surabaya, Jawa Timur",
    type: "station",
    lat: -7.2649,
    lng: 112.791,
  },

  // ===== PUBLIC PLACES & PARKS =====
  {
    id: "taman-suropati",
    name: "Taman Suropati",
    address: "Jl. Taman Suropati, Menteng, Jakarta Pusat",
    type: "general",
    lat: -6.1962,
    lng: 106.8288,
  },
  {
    id: "taman-menteng",
    name: "Taman Menteng",
    address: "Jl. Taman Menteng, Menteng, Jakarta Pusat",
    type: "general",
    lat: -6.1901,
    lng: 106.8345,
  },
  {
    id: "lapangan-banteng",
    name: "Lapangan Banteng Park",
    address: "Jl. Lapangan Banteng Timur, Sawah Besar, Jakarta Pusat",
    type: "general",
    lat: -6.1719,
    lng: 106.8327,
  },
  {
    id: "setu-babakan",
    name: "Setu Babakan (Betawi Cultural Village)",
    address: "Jl. RM Kahfi II No. 20, Jagakarsa, Jakarta Selatan",
    type: "general",
    lat: -6.3365,
    lng: 106.8497,
  },
  {
    id: "alun-alun-utara",
    name: "Alun-Alun Utara Yogyakarta",
    address: "Jl. Alun-Alun Utara, Yogyakarta",
    type: "general",
    lat: -6.7975,
    lng: 110.3664,
  },
  {
    id: "carfree-sudirman",
    name: "Sarinah Thamrin (Thamrin-Sudirman Corridor)",
    address: "Jl. M.H. Thamrin, Jakarta Pusat",
    type: "general",
    lat: -6.186,
    lng: 106.8235,
  },
];